'use strict';

const CONNECTION_STATES = Object.freeze({
  STOPPED: 'STOPPED',
  STARTING: 'STARTING',
  QR_REQUIRED: 'QR_REQUIRED',
  CONNECTING: 'CONNECTING',
  READY: 'READY',
  DISCONNECTED: 'DISCONNECTED',
  LOGGED_OUT: 'LOGGED_OUT',
  ERROR: 'ERROR',
  STOPPING: 'STOPPING',
});

module.exports = {
  CONNECTION_STATES,
};
